[[permission]]
identifier = "allow-app-commands"
description = "Allow application custom commands"
commands.allow = [
    "get_config",
    "save_config",
    "get_config_dir",
    "login",
    "fetch_triggers",
    "close_app",
    "quit_app",
    "open_devtools",
    "is_always_on_top",
    "toggle_always_on_top",
    "check_for_update",
    "install_update",
    "relaunch_app"
]
